-- Setup Player Potential Codes Table for Client-Side Randomization
-- This table stores the 'DNA' of player potential (codes like -10, -9)
-- The actual concrete PA value will be generated by the client when a new save is created.

DROP TABLE IF EXISTS player_potential_codes;

CREATE TABLE player_potential_codes (
  player_id INTEGER PRIMARY KEY,
  potential_code TEXT,            -- '-10', '-9', '-85', etc.
  min_pa INTEGER NOT NULL,        -- Lower bound of the range
  max_pa INTEGER NOT NULL,        -- Upper bound of the range
  club_tier TEXT,                 -- 'elite', 'top', 'normal'
  calculated_ca INTEGER NOT NULL, -- Baseline CA calculated from attributes
  speed_bonus INTEGER DEFAULT 0,  -- Bonus for high speed players
  FOREIGN KEY (player_id) REFERENCES players(id)
);

-- Populate the table based on FM2023 logic
INSERT INTO player_potential_codes (
  player_id,
  potential_code,
  min_pa,
  max_pa,
  club_tier,
  calculated_ca,
  speed_bonus
)
SELECT 
  p.id,
  
  -- 1. Determine Potential Code
  CASE
    -- Wonderkids (16-18)
    WHEN p.age <= 18 AND club_tier = 'elite' AND calculated_ca >= 100 THEN '-10'
    WHEN p.age <= 18 AND club_tier = 'elite' AND calculated_ca >= 80 THEN '-9'
    WHEN p.age <= 18 AND club_tier = 'top' AND calculated_ca >= 90 THEN '-85'
    WHEN p.age <= 18 THEN '-8'
    
    -- Young Stars (19-21)
    WHEN p.age BETWEEN 19 AND 21 AND calculated_ca >= 130 THEN '-85'
    WHEN p.age BETWEEN 19 AND 21 THEN '-75'
    
    -- Developing (22-24)
    WHEN p.age BETWEEN 22 AND 24 THEN '-7'
    
    -- Established
    ELSE NULL
  END as potential_code,
  
  -- 2. Determine Min PA
  CASE
    WHEN (p.age <= 18 AND club_tier = 'elite' AND calculated_ca >= 100) THEN 170 -- -10
    WHEN (p.age <= 18 AND club_tier = 'elite' AND calculated_ca >= 80) THEN 150  -- -9
    WHEN (p.age <= 18 AND club_tier = 'top' AND calculated_ca >= 90) THEN 140    -- -85
    WHEN (p.age <= 18) THEN calculated_ca + 30                                   -- -8
    WHEN (p.age BETWEEN 19 AND 21 AND calculated_ca >= 130) THEN 140             -- -85
    WHEN (p.age BETWEEN 19 AND 21) THEN 120                                      -- -75
    WHEN (p.age BETWEEN 22 AND 24) THEN 110                                      -- -7
    ELSE calculated_ca                                                           -- Fixed
  END as min_pa,
  
  -- 3. Determine Max PA
  CASE
    WHEN (p.age <= 18 AND club_tier = 'elite' AND calculated_ca >= 100) THEN 200 -- -10
    WHEN (p.age <= 18 AND club_tier = 'elite' AND calculated_ca >= 80) THEN 180  -- -9
    WHEN (p.age <= 18 AND club_tier = 'top' AND calculated_ca >= 90) THEN 170    -- -85
    WHEN (p.age <= 18) THEN calculated_ca + 70                                   -- -8
    WHEN (p.age BETWEEN 19 AND 21 AND calculated_ca >= 130) THEN 170             -- -85
    WHEN (p.age BETWEEN 19 AND 21) THEN 150                                      -- -75
    WHEN (p.age BETWEEN 22 AND 24) THEN 140                                      -- -7
    ELSE calculated_ca + 5                                                       -- Fixed
  END as max_pa,
  
  club_tier,
  calculated_ca,
  speed_bonus

FROM (
  SELECT 
    p.*,
    
    -- Club Tier Logic
    CASE
      WHEN c.name IN (
        'Real Madrid', 'Barcelona', 'Bayern Munich', 'Liverpool', 
        'Man City', 'Manchester City', 'Manchester United', 'Chelsea', 
        'Arsenal', 'Juventus', 'AC Milan', 'Inter Milan', 'Ajax',
        'Porto', 'Benfica', 'Paris Saint-Germain', 'Atlético Madrid',
        'Borussia Dortmund', 'Tottenham Hotspur', 'RB Leipzig',
        'Sevilla', 'AS Roma', 'Napoli', 'Valencia'
      ) THEN 'elite'
      WHEN c.name IN (
        'Leicester City', 'West Ham United', 'Everton', 'Newcastle United',
        'Real Sociedad', 'Real Betis', 'Lazio', 'Fiorentina', 'Atalanta',
        'Eintracht Frankfurt', 'Wolfsburg', 'Lyon', 'Monaco', 
        'Sporting CP', 'Braga'
      ) THEN 'top'
      ELSE 'normal'
    END as club_tier,
    
    -- Speed Bonus Logic
    CASE 
      WHEN (COALESCE(p.pace, 0) + COALESCE(p.acceleration, 0)) > 28 THEN 10
      ELSE 0
    END as speed_bonus,
    
    -- CA Calculation Logic (Simplified Weighted Sum for SQL)
    CAST(
      CASE 
        -- ST/CF
        WHEN p.position LIKE '%ST%' OR p.position LIKE '%CF%' THEN
          (COALESCE(p.pace, 0) * 3.5) + (COALESCE(p.acceleration, 0) * 3.5) + (COALESCE(p.finishing, 0) * 4.0) + (COALESCE(p.strength, 0) * 2.5)
        -- MC/AMC
        WHEN p.position LIKE '%M (C)%' OR p.position LIKE '%MC%' THEN
          (COALESCE(p.passing, 0) * 4.0) + (COALESCE(p.vision, 0) * 4.0) + (COALESCE(p.technique, 0) * 3.0) + (COALESCE(p.decisions, 0) * 3.5)
        -- DC
        WHEN p.position LIKE '%D (C)%' OR p.position LIKE '%DC%' THEN
          (COALESCE(p.marking, 0) * 4.0) + (COALESCE(p.tackling, 0) * 4.0) + (COALESCE(p.positioning, 0) * 3.5) + (COALESCE(p.jumping_reach, 0) * 3.5)
        -- Wingers
        WHEN p.position LIKE '%M (R)%' OR p.position LIKE '%M (L)%' OR p.position LIKE '%AM (R)%' OR p.position LIKE '%AM (L)%' THEN
          (COALESCE(p.pace, 0) * 4.0) + (COALESCE(p.acceleration, 0) * 4.0) + (COALESCE(p.dribbling, 0) * 3.5) + (COALESCE(p.crossing, 0) * 3.0)
        -- GK
        WHEN p.position LIKE '%GK%' THEN
          (COALESCE(p.reflexes, 0) * 4.5) + (COALESCE(p.handling, 0) * 4.0) + (COALESCE(p.one_on_ones, 0) * 3.5)
        -- Default
        ELSE
          (COALESCE(p.pace, 0) + COALESCE(p.acceleration, 0)) * 2.0 + (COALESCE(p.stamina, 0) + COALESCE(p.strength, 0)) * 1.5
      END
    AS INTEGER) as calculated_ca
    
  FROM players p
  LEFT JOIN clubs c ON p.club_id = c.id
  WHERE p.age IS NOT NULL AND p.age > 0
) AS subquery;
